// <auto-generated />
namespace BusTracker.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class qwer1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qwer1));
        
        string IMigrationMetadata.Id
        {
            get { return "201603081937285_qwer1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
